### ISSUE TITLE
Add Ability to record and easily check lists

### ISSUE THREAD

**Issue by Semiautomagic** [ThatRickGuy/PGSwiss#55]
A simple table that will tabulate the point costs ( for example we could add -5 for the caster then positive for the jacks units and solos,) This would allow, once web uploading is done, someone to check online to see what lists they played against and to make an online database of lists by player.

**Comment by fatzech** [comment]
List validation is a massive effort and time sink. I wouldn't ask TRG to use that much of his time to validate. While it would be nice, I believe its too much to ask of someone giving their free time to take on such an effort. If we really want to list check/validate then we can use excel or google spreadsheets as alternate options that already exist so he can devote more time to other enhancements. Not trying to flame or disregard any opinions, I am just familiar with how long it this stuff takes and as I get older my free time is precious :)

As an alternative (at small events usually under 16 players) I ask people to take a few minutes to email me their lists. Its fairly easy to copy and paste from WR2 now. Then list validation is done but your mileage may vary .... it can be like wrangling cats.

**Comment by ThatRickGuy** [comment]
I won't likely develop my own list validation, but luckily I game with the guy that developed Conflict Chamber. For the 2.0 version I want to build out significantly more of the web platform integration so that players can submit lists to the event if the TO has it set up ahead of time, and those lists can be verified through CC. 

I would love to get all that data, but as NekuraIzou mentioned, from a TO point of view, it doesn't help the event running. From a big data point of view though, there is a ton we could learn from it. So if/when it goes in, it will be completely optional.

**Comment by ThatRickGuy** [comment]
The Conflict Chamber integration is fully functional for list validation. Use the Conflict Chamber event system to have players pre-register. Morning of the event, from the conflict chamber site, download the event json. At the first screen of PG Swiss, click the Load from Conflict Chamber JSON button.
